### ISSUE TITLE
Developer Interview: Tiago Sousa

### ISSUE THREAD

**Issue by donbonifacio** [donbonifacio/blog#22]
Related to #19

**Comment by donbonifacio** [comment]
Hey Tiago, what can you tell us about what you have been doing at Sky?

**Comment by tiagomrsousa** [comment]
My work is a little bit wide, I can do a simple programming feature, but I can be evolved in an architectural decision or even propose a new approach to a problem. 
I'm part of the support team too, so I need to have a pretty good global vision of all our application. The phone rarely rings, but when it occurs I need to have the ability to look at logs, identify the problem and take the decision if is a critical one and need to be attack ASAP, or if a problem in an external service and  we need to contact other teams, or is a simple punctual problem and can be resolve in the next work day.
Internally I already worked in multiple teams, and in a couple of strategic projects, with lots of different persons so I considere I'm a lucky guy because almost every day I can learn something new with someone.

**Comment by donbonifacio** [comment]
So you've done lots of stuff on several teams, and you also worked with several team leaders I'm guessing. What's in your opinion the best and the worst traits of team leaders?

**Comment by tiagomrsousa** [comment]
I know this is a common expression, but is so true: _"A true leader should lead by example"_.
A good team leader should take care of the team, help each member growing up each in its own way. Do a good balance between what makes the team happy and what is required by the business. For example, you can't always ask the team to make and extra effort, to make the business happy, but sometimes is needed, and a good leader knows how to ask it and knows to reward it, and the reward don't need to be monetary, you just need to recognize the extra effort. 
For opposition I can say a bad leader is the exactly the oppose, but I can add something more. Having a leader who you feel he don't care with course of the project, who you feel he don't trust you or the team, who you feel he is more worried with himself, for me is a very short way to undermine the work final result.

**Comment by donbonifacio** [comment]
When you say that that a leader should lead by example, how much coding do you feel that the team leader should do? Should he be an authority on the technology side? How would you leverage a more technical manager against a manager that makes the team happier and more productive?

**Comment by tiagomrsousa** [comment]
I already had the 2 types of managers, and as a guy how likes technology I would say, a manager with coding skills is a nice to have but isn't the most important. Saying this I thing is fundamental a manager to have a technological background, otherwise how can he know if something is possible to be done, or how much time it should take, or how can he defende a point of view in a meeting?
When I said a leader should lead by example, it means a leader should listen to all members of the team, should know how to manage conflicts, should put the boots of each element of the team and the peoples who interact, and feel what they feel. A manager is a manager, is not a developer.

**Comment by donbonifacio** [comment]
That's a great description, that's for sure. Let's change then to things that managers should do. I see a manager with the responsibility of growing the team members. Imagine that in two years you are 10x better and more productive. What part should your manager have on that and how can he help you accomplish that?

**Comment by tiagomrsousa** [comment]
That's my normal :smile: :smile:  :smile: 
Jokes aside, everyone have things that likes more than other, if I'm doing something which I like sure I'm stimulated do to a good job, to investigate the best solution. A manager should know each element of the team, so if I like working with SQL the manager can give issues with SQL, if my colleague likes CSS he should do issues with CSS, and so on.
Challenging is a good way too, a manager knows the product have a problem and challenge the team to find a solution for it, looks like a child play, but is a very smart approach which result in every team element start to investigate, study, try to know better the product, the technology and probably will find some new trends capable of resolving the problem.

**Comment by tiagomrsousa** [comment]
Of course, in fact the most of the recognition a developer can achieve is because is a good communicator, explain clear and simple his ideas, is not because is a a great coder, don't be deceived. I already told to some colleagues - "You sell yourself very bad, you are great, but you don't know how to show to other persons.". You can't compartmentalise people skills, if you work with someone you have to  live with a good or bad developer, a good or bad team member, a good or bad friend, and so on, a person must be seen by the all package. If you ask me if I prefer to work with a great developer that is a despicable person, or a average developer which is a great team member, in a blink of an eye I will pick the second.
Like technical skill, communication skills, or other skill, is something you born with the predisposition, nevertheless you can train them. You can do soft skill formations, like coaching, you can learn reading books, there are an dozens of away you can develop your soft skills.

**Comment by donbonifacio** [comment]
I definitely agree with you. Thanks for your time answering my questions. It was really good to see your point of view and managers will learn something from it.

As a last question, anyone you'd like to suggest for me to interview next?

**Comment by tiagomrsousa** [comment]
It was for less than 2 years, but I worked with a young guy who marked me a lot, I look at him as a model of what I like to have as a team-mate. Is name is Manuel Felício, he is really brilliant, and every one around him learned a lot with him, technically he one of the bests I ever worked, and as a person he is always available to help everyone. Definitely he is a guy who you want to know a little more about is professional experience.
