### ISSUE TITLE
Manager Interview: Ricardo Vladimiro - Miniclip

### ISSUE THREAD

**Issue by donbonifacio** [donbonifacio/blog#53]
- [x] How do you train and coach new managers?
- [x] How do you train and coach experienced managers? What is required for you to level up?
- [x] How do you identify potential managers?

- [ ] Can you give some perspective on the value that you extract from data? I mean, how do you measure that value?
- [ ] Do you believe that most of business would benefit from getting value form data? What would be your advice to companies that don't do it yet. Where should they start?

- [ ] ~GPRD, impact on privacy and on data gathering~

**Comment by rvladimiro** [comment]
Hey!

My name is Ricardo Vladimiro aka Vlad and my official title at Miniclip is Data Science Lead. The Data Science Team is sort of a spin-off from the initial team I started, the Game Analytics and Data Science Team.

The objective of the Data Science Team is to research and develop Artificial Intelligence and Data Science data products that turn the large amounts of data we collect into value. This is a shift from using data as knowledge to support decision into data as an asset to generate value.

On top of that, Miniclip has a number of initiatives in the management space and I'm also heavily involved in training and coaching new managers and direct reports that are identified as potential managers.

**Comment by donbonifacio** [comment]
Can you talk a little about how you train and coach new managers? Is it personalised, or do you have a standard _template_ that you follow?

**Comment by rvladimiro** [comment]
Miniclip has an official manager training program. It's ran by the People and Organisation Team with an external company and it's fully structured. This program is tailored for general soft skills and leadership of existing managers at different levels of experience.

The management coaching that I'm involved in is different. For starters a Miniclip employee does not have to be a manager to participate. Any individual contributor that has shown interest or has been identified or any existing manager that wants to develop new skills is welcomed. There's a structure in the first 12 weeks but after that the topics for discussion are open and proposed by the group.

None of them are personalised. However these programs created a community of managers. This allows to managers that excel in some specific area to be identified which then allows for one to one ad-hoc coaching and discussion. This also has other positive implications like quicker discussion and adoption of new ideas but as far as personalisation goes, the manager's community nurtures it.

**Comment by donbonifacio** [comment]
How do you identify potential managers? And what traits to you value on managers?

**Comment by rvladimiro** [comment]
** NOT FINISHED YET **

Potential managers are often identified by their current line managers. Although this is the most common path it is also rather typical that individual contributors approach their managers or managers that, like me, are known to be involved in management coaching, to say they are interested in management. I think that one of the good things of this process is that they have the opportunity to understand what team management and leadership is in practice before committing to a career change.

I don't think we ever discussed which traits are we actively look for to identify potential managers but I can name some that are common on a Miniclip Manager and that are often found in potential managers.

- **Accountability.** This is more about being a Minicliper than it is about being a Miniclip Manager, really. Since the culture is very open and supportive, being accountable becomes second nature because we don't care about pointing fingers and punishing mistakes but rather to help to solve problems.

- **Not being afraid to say "I don't know".** Ok... maybe this one is something that I personally look for. "I don't know" is one of the most frightening sentences to say. Children learn to articulate around admitting ignorance since a very young age. As adults we have to actively learn to say it.

**Comment by donbonifacio** [comment]
We talked about how you find and train new managers. How about experienced managers? For example what would you require to level up?

**Comment by rvladimiro** [comment]
There are many different answers to this depending on the context. We can look at it from a pure theory perspective. Another option is to view it from each organisation point of view, e.g. from Miniclip's perspective. Since these are either too broad or too narrow, I'll give you my personal view on it.

As I see it, a proficient manager will look for continuous improvement to add value to the organisation. From what I can observe this continuous improvement is achieved in two different ways:

The first is **operational improvements**. I'll take a wild guess that this is not at all surprising for anyone reading. These improvements focus mostly on the team. Every time a manager changes a process, removes a bottleneck, improves communication, this is an operation improvement. These improvements are the hallmark of a more traditional approach to management. Often the manager looks for knowledge of process and project management, coaching, mentoring, etc. As far as Miniclip is concerned these are often discussions that start with a manager asking another manager "have you ever done X?" or "I know you tackled X in the past, can you walk me through it?" To answer your question of what would I require to level up in these improvements, I would answer seek for help with other managers, especially the more experienced ones.

The second way is through **innovation**. Unlike the first group, these managers look for processes, methodologies, views and ideas that don't exist in the organisation. They are the ones that create or bring something new to the organisation. While I expect that the majority of managers fall in the first way of improving, I strongly believe that a minority of managers, the ones that put a lot more effort and focus on management knowledge as one of their areas of expertise, should pursue and be empowered to try new things, whatever those are. Miniclip is a great example of this. Although the number of managers that fall in this category is small, they have the full support from the whole organisation. From localised experiments with new methodologies to set objectives to the creation of new teams, there's room for innovation. The management coaching that I referred previously and the two teams I started are great examples of this.

It's important to note that although innovation is "sexier" than ol'good operational improvement, it is not more relevant in my opinion. It gets more attention because it has the trademarks of things that are news worthy, like "disruption". It is extremely risky (to put it mildly) to have more innovation and disruption than good solid management improvement. It is also extremely risky to have no innovation and disruption though. This said, a balance is needed between the two and how that balance is attained depends on many factors.

**Comment by donbonifacio** [comment]
How do you know that the changes you are making are actually improvements? Naturally we can have a sense of how things are going on teams. I'm wondering if you have some more measurable ways of tracking performance. For individual contributors and for managers.

**Comment by rvladimiro** [comment]
Let me start by arguing against "having a sense of how things are going". Having a sense is opinion based and it is extremely difficult to reason about. As an example, you can have a team that you, as a manager, feel is going great. You infer that from individual contributors growing over time, from meeting deadlines and reaching objectives. What if that team is a support team that acts as an internal service provider and your team's objectives are not aligned with the objectives of the team that it serves? What happens when a manager of one of the teams your team serves has a sense that your team is not delivering what they need, or in other words, that your team is not adding value to them? This will be a very difficult conversation to have because it is mostly based on opinion and lack of communication to begin with.

For this reason I steer away from opinion based sense or feeling and try my best to align specific objectives with the business and/or other teams. And, in my opinion, this is where we measure the impact. It's easier in theory than it is in practice. Let me give you an example.

Imagine the following scenario, team A consistently misses delivery deadlines they set. The easy solution is to establish a new methodology but lets assume this is not the right thing to do. According to team A the delays happen due to a communication problem with team B. To make things a bit more complex let's assume that there's a team C that is responsible for the communication. Now we have several objectives to be met:

- Team C has to deliver a solution for the communication problem and this solution has to meet the needs of both teams A and B
- Team A has to meet delivery deadlines after the communication problem is solved

The end improvement we are looking for is that team A delivers by the deadlines they set which aligns them with the company objectives. But to get there we need all the teams to establish objectives and priorities for a timely solution. No matter how we look at it though, the end result we want to see is that team A delivers on time without changing the methodology of estimating deadlines. We can set this as a boolean or measure the rate of successful deliveries. If management overhead is a concern, a boolean is sufficient, if not success rate is preferable.

This example is very operational but the same logic can be applied to more disruptive changes especially if you use OKRs which allow for much shorter, focused and ambitious objectives.

**Comment by donbonifacio** [comment]
Could you elaborate on using OKRs for much shorter, focused and ambitions objectives? Do use OKRs or something similar? Are you able to successfully communicate with individual contributors what's expected from them?

**Comment by rvladimiro** [comment]
OKRs are relatively new in Miniclip. Interestingly their introduction was what I described earlier as innovation. There was a wide discussion on the topic of objectives and one manager proposed to his own manager the use of OKRs. His manager was involved in several of the objectives discussions and brought it up. It spread to more managers that then advocated it to executives who gave full support for it to be tested. It is currently being tested across several teams.

Each team is implementing OKRs differently. Some are using it as a form of making objectives more agile disregarding some parts of it for either simplicity or because those parts are not considered to add value at this point in time, others are trying a full "by the book" implementation. Given this varied experience, I'll answer your question in the context of the BI department in general and the Data Science team in particular. The best way to illustrate is to compare before and after.

Before OKRs we would plan the whole year. Inevitably this meant that Q1 was filled with the most urgent objectives, Q2 and Q3 with the "next in line" and Q4 with the "nice to have" ones. The problem with this is that companies like Miniclip are extremely agile and adapt very quickly to many external factors and rightfully so. While all Q1 and most Q2 objectives were usually delivered, by Q3 and Q4 the agreed objectives were often irrelevant. We often found ourselves in the position of excusing objectives not being met on the basis that there were other more urgent unplanned objectives. This had another issue attached to it which was the link between objectives and performance review.

With OKRs we solve most of these problems. We plan every quarter for the next two quarters. I'm aware that this is not exactly the OKR way but both Data Engineering and Data Science have projects that would not fit a one quarter window. In true OKR fashion, we don't link performance to objectives which means that in case the business needs us to adapt we happily adapt too even if we have to adapt less given that we plan and review every quarter. The keyword is focused. What we are saying when go through our quarterly OKRs is "this is the plan we have to deliver maximum possible value in the next quarter". Shorter and ambitious are a function of focused.

I have not found any difficulties in the communication with individual contributors because they are part of the discussion. The typical process is the following. All Miniclip employees are informed of the objectives and vision of Miniclip for the following year. This is usually followed by many informal discussions between the Head of BI, managers and individual contributors. These are held in one-on-ones, staff and manager's meetings and it is a natural process where ideas, doubts and answers go up and down over time. This then trickles down in the form of OKRs. There are department level OKRs for the BI and those are owned by BI managers. Then there are team level OKRs that can be owned by anyone. There are no individual contributor OKRs although it is common for a team level OKR to be  owned by individual contributors.

I never really gave any thought on why this was an easy process to communicate and implement but on hindsight I would say that it's extremely easy to communicate about something to a person when that person is part of it.

**Comment by rvladimiro** [comment]
**INCOMPLETE**

This is fairly new and something I'm still debating and discussing. I'll share my current point of view but take it with a grain of salt.

To start with I really like the vision of our Head of People and Organisation. The starting point for performance is the tasks you execute and that you were hired to do. Those are rarely, if ever, written down as objectives, e.g. as a manager conducting performance reviews is part of my tasks but that was never set as an objective. However failing to perform these tasks is basically the definition of under performance. Then there is a layer around these tasks that includes objectives but also other things individual growth. The third and final layer is what distinguishes the high performers of solid performers. It deals with the context, e.g. a new initiative or delivering projects in particularly difficult situations.

From this description it is almost immediately clear that objectives are just a part of one of the layers of performance. This is especially true when the objectives of a team are not directly correlated with an actual financial figure. For instance we can argue that the sales objective of a sales team is directly correlated with the financial figure of a company. But we can as easily argue that setting

**Comment by donbonifacio** [comment]
Your one-on-ones seem very interesting. What's your approach to one-on-ones? Do you plan for them? What value do you aim to take from them? What tips would you give to a new manager starting to do one-on-ones?

**Comment by rvladimiro** [comment]
My current take on one-on-ones is very similar to the one explained in Manager Tools (https://www.manager-tools.com/) and I recommend any manager, new or experienced to check it out if they don't know it. A full disclaimer is in order before I continue: I am not affiliated with Manager Tools or their services but I am their customer for many years. My tip is to listen to Manager Tools Basics and keep in mind that they work with major companies. For this reason it's more important to understand the "why" and then adapt the "how" to your particular scenario. Manager Tools "by the book" works better in large standard organisations. For other organisations, like fast growth tech companies and startups the "how" is, from my experience, too formal. The "why" is great though.

The #1 objective of one-on-ones is to develop a relationship with the direct report. That is the value I wish to generate. It is not a reporting meeting, I personally find individual report meetings unnecessary and a sign of micro-management. One-on-ones are the time each direct report has my full attention. I have heard direct reports I managed scheduling other meetings in a way they didn't conflict with our one-on-ones because and I directly quote "one-on-ones are sacred".

The problem of getting managers to have great one-on-ones is that it takes some months to actually see the full benefit of these meetings, assuming they are doing it right and focusing on relationship instead of reporting.

My "rules" for one-on-ones are:
1. Weekly pre-scheduled 30 minutes meetings. I won't reschedule a one-on-one meeting unless there's a meeting with a lot of people and my presence is absolutely necessary. 
2. The direct report has the first block (10 to 20 minutes) to speak about whatever they want. And I literally mean whatever. It is difficult to express how important this is but in a nutshell the growth of my direct reports is not purely professional. Their life outside the office is at least as important as their life in the office for their professional productivity and growth. If they only want to talk about work it's fine too, of course and many actually do.
3. I have the remaining time for whatever I want to discuss.
4. I only have one-on-ones when I have more than one direct report. There are a number of reasons for this but for the most part when I have one direct report, the daily interaction is closer to a buddy system, hence the one-on-ones tend to have a lot of "like I told you yesterday".

All my direct reports know of all the rules, including the reasons for them.

I do prepare for one-on-ones. I have a notebook with a tab for each direct report. Every point that appears over the week that I want to discuss is written there. The day of the one-on-one I review my notes of the previous one-on-one and the new notes and go to the meeting.

One-on-ones are a huge topic. One that is too complex to explain in this format I think but I hope I got enough of the basics.

**Comment by donbonifacio** [comment]
This interview was great and I learned a lot. Thanks for participating. :)

To close this interview, what topics would you expect to see in a blog about engineering management? And do you have someone to suggest for a next interview?

**Comment by rvladimiro** [comment]
Thank you, I have a lot of fun answering the questions.

Regarding topics for the blog, I'd love to read more about adapting to technology changes.

As far as suggestions, there are two people with whom I discuss management for a long time. The first one is Ricardo Sousa. We are friends for almost 30 years and we've discussing and learning management from each other for almost 20 of those years. The second is Gilberto Medeiros who was the starter of the management coaching initiative at Miniclip and is one of the best managers I had the opportunity to work with.
