### ISSUE TITLE
Recruiter Interview: Gonçalo Sequeira - Mercedes-Benz.io

### ISSUE THREAD

**Issue by donbonifacio** [donbonifacio/blog#55]
Pipeline
- [x] You also mentioned the motivational part of an interview. How do we make sure we're properly selling our company?
- [x] What can candidates to to stand out?

**Comment by donbonifacio** [comment]
Hey Gonçalo, can you talk a bit about Mercedes and the work you do?

**Comment by GFSS7** [comment]
Hello Pedro! First of all thanks a lot for inviting me for this interview, I have been reading your blog posts and they are quite different from the others in the portuguese market, so it’s my pleasure to be interviewed by you.  

Going directly to the question, Mercedes-Benz.io is a new company of the Daimler group, Daimler has companies like Mercedes-Benz, AMG, Mytaxi and other powerful brands related with cars, trucks or vans. Daimler really knows how to make a good car but isn’t that good to produce digital products and that’s why they decide to create us. 
Mercedes-Benz.io builds high quality digital products exclusivly to Mercedes-Benz. We work mainly with web products with technologies as Java and Spring on the backend side and frameworks like Vue.js or React for the frontend. We have two more offices, one in Stuttgart and other in Berlin, usually we have distributed teams working in the same product.

My mission here is to recruiter the best people to delivery those products, mostly tech people. I was the second member to joined the team and I had the chance to help the company grow since the first day. Besides recruiting I have the responsibility to organise and plan events like meetups, job fairs and professional events to improve our employer branding in the market. Since we are a new company and we act like a start-up (but back-up by a Big company) sometimes I have a couple of other responsibilities but not so often as those two.

**Comment by donbonifacio** [comment]
Starting a new development hub can he a daunting experience. What guidelines can you give to someone in a similar situation?

**Comment by GFSS7** [comment]
I wouldn’t say that, starting a new hub in Portugal, is one of the most challenging, interesting and demanding experience that I had in my career so far. :) 

One of the things that everyone says is that the first 5~10 people are really important, and they are really a must, if you hired A players you can get more As and Bs player after, if in the first 10 hires you make a mistake, that will impact all the efforts that you will do. 
Besides the importance of the first hires, the first Leader is determinant If you can’t find a amazing one you won’t get many good people onboard.
In the case of Mercedes-Benz.io we had the help of having a great brand behind us for some companies not so lucky, I would advise the following:

Hire a great Leader 
Hire great engineerings but make sure they are good technically and they fit the culture that you and the leader that you choose want 
Have a great product or project to show but also reveal the not so good aspects that your product/project/company has. 
Give feedback to every candidate that you talk with, if you want to grow a lot you need to create relationships while you are hiring.


If you can complete the 4 steps above you will have a much easier life, however the mission is still hard since we have so many companies looking for the same type of Talent right now.

**Comment by donbonifacio** [comment]
How do you find great leaders? :) Or a more fair question: how would you tell if someone is a great leader?

**Comment by donbonifacio** [comment]
Starting a new hub means a lot of processes and new things that need to be defined. What guidelines would you give in terms of defining a recruitment process?

**Comment by GFSS7** [comment]
That’s totally true but is also true that, in the beginning, you don't have a lot of time to define every thing in the way that you wish. 

To define a good recruitment process you need to talk and involve a lot of people (stakeholders). 
First you need to understand which roles the business demand and why they need them. Following, you need to make sure those roles are important and that they will have an impact in the organization. You also need to have a good understanding of the technical skills and the level of expertise really needed, everyone will tell they want the best in the market but most of the cases it isn’t true. Of course it is also crucial to know properly your “clients” and understand which type of soft-skills they value more.
After understanding the roles and their specification you should see how your competitors are doing and “copy” the good practices and change the bad things about it. 

Having a good network, that may include other recruiters and developers, can help you with the information you need, then it really depends on the roles you’re searching for, yet the process shouldn’t be too easy neither too hard and not too fast but not too slow, seems standard but without a balance you will lose people. If you are recruiting IT, you must have a technical challenge/test, the complexity will depend on your target but I think it is a must if you want to recruit great developers. 
Besides that consider investing your time to do behavior/motivational interviews, be sure (or be close to that) if the person that your are hiring will be integrate easily in your team, “sell” your company well, I recommend at least one hour conversation, this will improve not only your hirings but also your retain in the future.

**Comment by donbonifacio** [comment]
Can you elaborate on the behaviour part? How do you assess if a candidate is a match?

**Comment by GFSS7** [comment]
Assessing soft-skills is never easy, if you saw a couple of different job
descriptions almost every company is looking for someone proactive,
flexible, organized self-learner with good communications skills who can
learn quickly...so we are mostly looking for the same buzz words but then
every company has their own definition of this type of skills accordingly
with their culture.

To evaluate some of those skills we can find “facts” about the person
through behavior, puzzles or situational interviews / questions or you can
find a more hard prove as referrals, grades or certifications.

However an human being is not only made of concrete things, we are rational
and emotional at the same time so our gut feeling is very very important in
the decision making of a match. You can also improve your gut feeling with
time, experience and observing repetitive behaviors in the employees. Most
of the engineers won’t realise it in the beginning because they are more
rational than emotional but the emotition is what makes the work fun and
also creates a great team spirit when you have the right culture and the
right people.

So in a short way, you should have facts that the person in front of you is
good and your gut feeling should tell you the same, if you feel something
is wrong and you can't explain why, it’s because something in your
subconscious is telling you he isn’t the right fit.


2018-07-19 16:50 GMT+01:00 Pedro Pereira Santos <notifications@github.com>:

**Comment by donbonifacio** [comment]
You also mentioned the motivational part of an interview. How do we make sure we're properly _selling_ our company? If most companies mention those buzz words and great culture, how can we make a difference and stand out?

**Comment by GFSS7** [comment]
That one is easy for me because I don't understand why companies act this
way. As you said most companies mention those buzz words, "we are cool, we
have ping pong,we are flexible and agile bla bla bla..."

Of course that you can and should mention all that if they are true,but
besides that you need to tell them your "problems", or as I like to say,
the challenges in your organization.

For exemple, If you aren't 100% Agile, say it to a Scrum Master, if you are
recruiting a Head or a Team leader for a difficult or complex area, share
some of the team problems. By doing this you will improve your chance of
gaining the candidate trust and also help them being more aware of the
company's reality. People with the right information make better decisions,
if you want to convince someone that your company is a good place to work
you also need to talk about the "not so good" aspects. People are not
perfect neither organizations :)



2018-07-27 8:53 GMT+01:00 Pedro Pereira Santos <notifications@github.com>:

**Comment by donbonifacio** [comment]
So you're telling me that a way to stand out is to he honest and present our problems and issues? :) I do like that. Any other out of the box tips? For example, what could a small startup that no one knows about do to fight for talent with bigger brands?

**Comment by GFSS7** [comment]
yes, seems easy right? :) well depending on the startup purpose. If we are
talking about a startup that wants to go from 10 to 50 people , you should
send your best developers to every meet-up at your area of expertise. You
need to create a good relationship with comunities to be able to have
access to the best talent. If you want to grow more, let's say +100, you
should not only do that, but also bet a lot on Universities with different
types of initiatives, not merely jobfairs. You have a lot of cool stuff to
do with young talent, you can do opendays, workshops at universities,
Hackthons and so on, Those are just a couple of thoughts because I never
had to manage the recruitment of a small startup so far.

2018-08-08 19:12 GMT+01:00 Pedro Pereira Santos <notifications@github.com>:

**Comment by donbonifacio** [comment]
And from the candidate point of view. What can candidates do to stand out?

**Comment by GFSS7** [comment]
The candidate should follow the same approach. I see recruitment as the
start of a relationship, if one side lies, even if the other side doesn't
notice that, trust won't be builded and it won't last long. The candidates
should also research more about the companies in order to do more and
better questions during the interview process, if so, they will be able to
gather more information and be more certain if the company is the right or
wrong choice for them.

Pedro Pereira Santos <notifications@github.com> escreveu no dia sexta,
10/08/2018 à(s) 10:01:

**Comment by donbonifacio** [comment]
Thanks for answering my questions. To close this interview, could you suggest some topics that you'd like to see related with engineering management? And would you suggest someone for me to interview next?

**Comment by GFSS7** [comment]
It was a pleasure to have this interview with you. I don't have an exciting
topic to suggest but I would like to suggest André Macedo, Senior Software
Engineer at Mercedes-benz.io for you to interview!

P.S I already spoke with him and he is willing to do it :)

Pedro Pereira Santos <notifications@github.com> escreveu no dia terça,
4/09/2018 à(s) 11:11:
