### ISSUE TITLE
Coach interview: Monika Wojtasinska-Felicio - TEAMmatters

### ISSUE THREAD

**Issue by donbonifacio** [donbonifacio/blog#73]

**Comment by donbonifacio** [comment]
Hey Monika, can you give an intro to your background and about what you do?

**Comment by monikawfelicio** [comment]
Sure.

My professional background is related to change & project management focused on Organizational Development. I help passionate leaders develop strong and healthy organisations implementing meaningful changes. One of my main inspirations for the "end result" of my work is a culture and a structure that helps a company operate in the [Modern Agile](https://www.agilealliance.org/resources/videos/modern-agile/) manner.

I gained a vast part of my experience in a consulting company in Poland working on different HR and strategic change management projects for multiple companies – among others: Polish airlines, national railways, companies from the energy or telco sector etc. but earlier I also worked in HR departments of an IT company, a bank or a brewery;) 
I loved the consulting work, but its crazy intensity (consulting is known for it) made me decide on a life change. I moved to Portugal (also because of my Portuguese husband) and here I started working on the similar matters, but independently. I created the brand Team Matters that I want to develop further. I facilitate workshops and manage change projects. So far, my biggest pride comes from my almost 4-year cooperation with 7Graus where we implement Modern Agile and we are heading for an ambitious vision. I think that we have been doing pretty well ;)

Regarding my educational background, I graduated from Economy 11 years ago, doing my master in HR (today I would say in People and Culture;)) and ever since I’ve been extending my psychological knowledge through a few post graduations, namely in Group Facilitation, Psychology & Methods of Project Management, and Job Coaching. 
I love learning! ;) Therefore I also have a few certifications such as in Change Management (by PROSCI), Management 3.0 and some psychometrical tools (like MBTI Step 1 & Step 2, Extended DISC). I also continuously learn and test in practice different tools that can facilitate team dynamic in a bit unusual yet fun and engaging way, like Lego Serious Play, Points of You cards (known also as The Coaching Game) or methods like Design Thinking. 
It’s just to give you a broader overview and some examples.

(If it's too much we can cut later and just paste a link to my LinkedIn profile ;))

**Comment by monikawfelicio** [comment]
[Modern Agile](url)

**Comment by monikawfelicio** [comment]
I look forward to your feedback and the next question :)

**Comment by donbonifacio** [comment]
That's awesome Monika. How do you help leaders? And what kind of changes do you help implement?

**Comment by monikawfelicio** [comment]
We could say I play “intellectual tennis” with them ;) When requested, I offer a second opinion on people-related topics and organizational dilemmas they have, indicating a set of possible solutions. I both advise and execute them, if needed, which may happen, for example, by facilitating workshops or through individual coaching.

I help bring light to human behaviour and individual differences, which helps manage diversity in the team and increase inclusion. At the same time, it helps the leader to understand himself better and become more self-aware and confident in his leadership style. I think that, along the way, the leader learns how to be himself, and better. He doesn’t need to “_play_ the role of a leader”; trying to be someone he’s not; he just needs to be authentic so people can **trust** him. Because I believe that you can’t effectively lead from a position of power but only through the authentic relationships you have with each member of your team. That’s why I believe it’s so important for a leader to know himself and master self-management first before he will try to better manage or influence others. Only with good self-awareness, we can focus on building relationships and trust with others - then, team management and leading changes are easier. And trust, here, is fundamental. All this to build organizational with no politics, toxicity or misplaced talents, but with a clear purpose and the right people, so you can focus on your organizational adaptability, growth and excellence.


There is a quotation of John Adair that I very much agree with: “You can be appointed a manager... (but) you are not a leader **until** your appointment has been ratified in the hearts and minds of those involved.” 


The second part of the question - about the kinds of changes.

In general terms, I help to implement changes both at the individual and cultural/organizational levels. By changes, I mean systemic solutions that address problems like:
» How can we be more effective?
» How can we improve teamwork and team collaboration?
» How can we motivate/engage people in their work?
» How can we recognize efforts without a traditional, “toxic” appraisal system?
» How can we have more people with the Agile or growth mindset?
» How can we get people to take more responsibility/ownership?
» How can we encourage people to hold each other accountable?
» How can we transform to be more Agile?

How do I do it? I start with a diagnosis that helps me understand both the leader and the team. I am usually there to make something work better. So it’s a little bit like with a doctor - I listen to the symptoms but I also do some additional analysis to confirm or verify the accuracy of the assumptions (interviews or workshops with the team, surveys etc). Then, I suggest a set of potential tools or ways to address the real cause of “the pain” and we execute the “prescribed” treatment. I work in a very participative way, so I see myself as a facilitator of change - helping the leader and the team co-create and adapt the final solution to their specific context. I do it _with_ them, not _to_ them.


Does that answer your question? Or would you like me to be more specific on something? :)

**Comment by donbonifacio** [comment]
It's pretty good (maybe I'll split this in the two questions I asked).
Next:
How about working with leaders of leaders? Is the approach different?

**Comment by monikawfelicio** [comment]
_:) 
Your question stopped me and made me curious. What would you think could/should be different?:)
Here, if it was a live conversation I would really like to know your opinion and understand first what triggered you to ask the question?? :) 

And normally I would wait to listen to your answer first, however, following the convention of the interview and not to make it look as avoidance to the answer ;) I can say that...:_

In my opinion what differentiates them most often is just the level they operate on - more strategic vs operational - but not so much the consciousness they all need to understand the concept of authentic leadership - who they are, who they are not ;) and how to understand diversity of people, and navigate among complexity of their interactions to get together to the common vision.

_What is your point of view on the leaders of the leaders and their challenges, Pedro?_

**Comment by donbonifacio** [comment]
This is actually something that puzzles me. In theory everything should be similar, but if we're being a line manager of a manager, there are different things to consider.  I may know how to grow a developer, how to push him to be better. But I may not know how to grow a manager and make him better. How to know if he is doing a good job and being a good leader? How to know if we're all aligned in values and have a healthy culture going on. Specially if we are leading several leaders.

Maybe it's a question of scale. How do you scale coaching? Imagine that instead of coaching someone, you're actually in charge of making sure that good coaching and leadership is happening at the company. Any tips or pointers?

**Comment by monikawfelicio** [comment]
Now I can understand you better and I can see a few different plots here that I would like to relate to with more time. I will try to reply to your question over the weekend. Ok?

**Comment by donbonifacio** [comment]
Ok. Please do. :)

**Comment by donbonifacio** [comment]
(I think this is going great, just keep going and do as you please. And give me some time to come up with the next question :)

**Comment by donbonifacio** [comment]
Yes that answers my question and clarifies several things for me. 

On the document you referenced, you have smart organisations (technology, strategy, marketing, finance, ...) and healthy organisations (minimum politics and confusion, high degree of moral and productivity, low turnover, ...). Can an organisation be both smart and healthy? How do you sell the healthy mindset?

**Comment by monikawfelicio** [comment]
lol - 1mln dollar question! :) (How do you sell the healthy mindset? - Me or a leader in an organization?;))

I will answer during next few days. This week is a bit busy for me.

**Comment by monikawfelicio** [comment]
We don't have a strict deadline for the whole interview, do we?

**Comment by donbonifacio** [comment]
Nop. Take your time. :)
But I'll nag you if you start taking too long to reply. ;-P

**Comment by monikawfelicio** [comment]
I think that we can only sell the healthy mindset to those that want it and are ready to buy ;)

An organization is like an organism. You can either exploit it to death or take care of it so it can creatively keep exploring the world of opportunities. 

Like every organism, organizations need balance. They need to be smart AND healthy. In order to stay in the game, they need processes, results AND healthy habits. 

In many companies, there is a visible dominance of one of these dimensions. But, as with every extreme, there are some risks attached to it. What I can see most often is that organizations that focus only on the smart part (tasks and results) end up with a pretty toxic work environment. Many people hate working there, there is high internal competition, high rotation, low level of trust or commitment and accountability level close to zero.

On the other hand, when a company focuses only on the internal issues (healthy habits and well being of people) it may oversee external opportunities which, after all, determine its existence in the business world.

Therefore, I believe that both elements are important. Balance is crucial. Finding it is an active and continuous process. Because it's a living organism with complex and dynamic interactions between all the parts - both processes and people. A change in one part of the system brings a new impulse or energy to the rest. It requires attentive observation. Continuously. Like in a family or a relationship. We all evolve. And so do organizations.

In a way, it may sound a bit abstract, but I think this is exactly what is very well pictured in the Modern Agile model. You can see there both the smart aspects of your business (the horizontal axis with “Experiment and learn rapidly” + “Deliver continuous value”) and the healthy social interactions within the ecosystem of your organization (the vertical axis with “Make people awesome” and “Safety as a prerequisite”).

In my opinion, balancing the two is super important because it determines the overall vitality of the whole system. It also determines the quality of its existence.

It's possible. And it can double your results. I witnessed it.
I have contributed to organizational and cultural evolution that allows pursuing the balance and I can share with you my final conclusion. It is only possible to do that with a conscious and passionate leadership team that is ready to "buy" and execute the healthy mindset. This is the critical condition, in my opinion.

What we can try to do is to make sure the leaders are aware of this duality (smart vs healthy) and the benefits of balancing the two. Then, we can verify their desire and willingness to experiment with it. Only then we can start discussing how to do it.

**Comment by donbonifacio** [comment]
Amazing. I do agree with you and my way of seeing things is very aligned with yours. Even if I can't organise my ideas on these topics as well as you do. To close the interview, my typical final questions: what topics would you expect to see on an engineering management blog? And would you suggest someone for me to interview next?

**Comment by monikawfelicio** [comment]
Thank you Pedro for your feedback. It's very valuable for me. And thank you for having me here.

About the topics I would expect - I like the variety of topics and people you interview. I don't have any expecation. I read  every post with curiosity. My only wish is that you keep it authentic, practical and inspirational - the way you do it now (for as long as it brings you joy and satisfaction;)).

About a person to interview - how about [Pedro Pereira Santos](https://www.linkedin.com/in/donbonifacio/)? Maybe you could create an AMA post (ask me anything) and this way we could interview you? :)
